//<auto-generated />

using System.Threading;
using System.Threading.Tasks;
using Refit;
using TestWebApi.Models;

namespace Test.Name.Space
{
    public partial interface ITestWebApiMinimalApiApi
    {
        [Post("/weather-forecast")]
        Task<IApiResponse> PostWeatherForecast([Body] WeatherForecast forecast, CancellationToken cancellationToken = default);
    }
}