//<auto-generated />

using System.Threading;
using System.Threading.Tasks;
using Refit;
using TestWebApi.Models;

namespace Test.Name.Space
{
    public partial interface IWeatherForecastApi
    {
        [Get("/weather-forecast")]
        Task<IApiResponse<WeatherForecastRecord[]>> GetWeatherForecast(CancellationToken cancellationToken = default);

        [Get("/weather-forecast/with-name")]
        Task<IApiResponse<WeatherForecastRecord>> GetSomeWeather(int days, CancellationToken cancellationToken = default);
    }
}