<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Verify.NUnit" Version="31.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GenerateAspNetCoreClient\GenerateAspNetCoreClient.csproj" />
    <ProjectReference Include="..\TestWebApi.Controllers\TestWebApi.Controllers.csproj" />
    <ProjectReference Include="..\TestWebApi.MinimalApi\TestWebApi.MinimalApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**\*.verified.cs" />
    <None Include="**\*.verified.cs" />
    <Compile Remove="**\*.received.cs" />
    <None Include="**\*.received.cs" />
  </ItemGroup>

</Project>
